import "dotenv/config";
import { PrismaClient } from "@prisma/client";
import { PrismaLibSQL } from "@prisma/adapter-libsql";
import { createClient } from "@libsql/client";

const client = createClient({
  url: process.env.TURSO_DATABASE_URL ?? "file:./dev.db",
  authToken: process.env.TURSO_AUTH_TOKEN,
});
const adapter = new PrismaLibSQL(client);
const prisma = new PrismaClient({ adapter });

async function main() {
  // Clear existing data
  await prisma.comment.deleteMany();
  await prisma.taskBar.deleteMany();
  await prisma.task.deleteMany();
  await prisma.phase.deleteMany();

  // Create phases
  const phases = await Promise.all([
    prisma.phase.create({
      data: {
        id: "onboarding",
        name: "Onboarding",
        startWeek: 14,
        startYear: 2026,
        endWeek: 18,
        endYear: 2026,
        color: "#3B82F6",
        order: 1,
      },
    }),
    prisma.phase.create({
      data: {
        id: "acceptatieconv",
        name: "Acceptatieconversie",
        startWeek: 19,
        startYear: 2026,
        endWeek: 26,
        endYear: 2026,
        color: "#8B5CF6",
        order: 2,
      },
    }),
    prisma.phase.create({
      data: {
        id: "testen_acc_h",
        name: "Testen & Acceptatie Hof",
        startWeek: 27,
        startYear: 2026,
        endWeek: 35,
        endYear: 2026,
        color: "#F59E0B",
        order: 3,
      },
    }),
    prisma.phase.create({
      data: {
        id: "trainen_hof",
        name: "Trainen Hof",
        startWeek: 36,
        startYear: 2026,
        endWeek: 39,
        endYear: 2026,
        color: "#10B981",
        order: 4,
      },
    }),
    prisma.phase.create({
      data: {
        id: "livegang_hof",
        name: "Livegang Hof",
        startWeek: 40,
        startYear: 2026,
        endWeek: 44,
        endYear: 2026,
        color: "#EF4444",
        order: 5,
      },
    }),
    prisma.phase.create({
      data: {
        id: "trainen_st",
        name: "Trainen Stedelink",
        startWeek: 45,
        startYear: 2026,
        endWeek: 47,
        endYear: 2026,
        color: "#10B981",
        order: 6,
      },
    }),
    prisma.phase.create({
      data: {
        id: "livegang_stedelink",
        name: "Livegang Stedelink",
        startWeek: 48,
        startYear: 2026,
        endWeek: 50,
        endYear: 2026,
        color: "#EF4444",
        order: 7,
      },
    }),
    prisma.phase.create({
      data: {
        id: "trainen_livegang_hef",
        name: "Trainen en Livegang Hef Wonen",
        startWeek: 51,
        startYear: 2026,
        endWeek: 13,
        endYear: 2027,
        color: "#6366F1",
        order: 8,
      },
    }),
  ]);

  console.log(`Created ${phases.length} phases`);

  // Create tasks
  const taskDefs = [
    {
      id: "group-3-0",
      projectNumber: "3.0",
      description: "Proefconversie",
      owner: "",
      phaseId: "onboarding",
      isGroupRow: true,
      status: "not_started",
      barType: "task",
      startWeek: 15,
      startYear: 2026,
      endWeek: 18,
      endYear: 2026,
      isMilestone: false,
      sortOrder: 10,
    },
    {
      id: "task-2-11",
      projectNumber: "2.11",
      description:
        "Aanlevering vastgoedtabel gevensv tbv VGT 3 corporaties (ex WwD)",
      owner: "Faridda",
      phaseId: "acceptatieconv",
      isGroupRow: false,
      status: "not_started",
      barType: "task",
      startWeek: 19,
      startYear: 2026,
      endWeek: 24,
      endYear: 2026,
      isMilestone: false,
      sortOrder: 20,
    },
    {
      id: "task-2-12",
      projectNumber: "2.12",
      description:
        "Migratie bezit (VGE en VHE) vastgoedtabel 3 corporaties",
      owner: "Arnoud",
      phaseId: "acceptatieconv",
      isGroupRow: false,
      status: "not_started",
      barType: "task",
      startWeek: 20,
      startYear: 2026,
      endWeek: 26,
      endYear: 2026,
      isMilestone: false,
      sortOrder: 30,
    },
    {
      id: "task-2-13",
      projectNumber: "2.13",
      description:
        "Controle vastgoedtabel 3 corporaties (VGE en VHE)",
      owner: "Faridda",
      phaseId: "acceptatieconv",
      isGroupRow: false,
      status: "not_started",
      barType: "task",
      startWeek: 21,
      startYear: 2026,
      endWeek: 26,
      endYear: 2026,
      isMilestone: false,
      sortOrder: 40,
    },
    {
      id: "task-2-14a",
      projectNumber: "2.14",
      description: "Aanlevering WvD voor 3 corporaties",
      owner: "Faridda",
      phaseId: "acceptatieconv",
      isGroupRow: false,
      status: "not_started",
      barType: "task",
      startWeek: 20,
      startYear: 2026,
      endWeek: 23,
      endYear: 2026,
      isMilestone: false,
      sortOrder: 50,
    },
    {
      id: "task-2-14b",
      projectNumber: "2.14",
      description: "Aanlevering GRIP en CRM Hof Wonen",
      owner: "Faridda",
      phaseId: "acceptatieconv",
      isGroupRow: false,
      status: "not_started",
      barType: "task",
      startWeek: 21,
      startYear: 2026,
      endWeek: 24,
      endYear: 2026,
      isMilestone: false,
      sortOrder: 60,
    },
    {
      id: "task-2-15",
      projectNumber: "2.15",
      description: "Migratie WvD in vastgoedtabel voor 3 corporaties",
      owner: "Arnoud",
      phaseId: "acceptatieconv",
      isGroupRow: false,
      status: "not_started",
      barType: "task",
      startWeek: 22,
      startYear: 2026,
      endWeek: 25,
      endYear: 2026,
      isMilestone: false,
      sortOrder: 70,
    },
    {
      id: "task-2-16",
      projectNumber: "2.16",
      description: "Migratie Databalk GRIP en CRM corporatie Hof Wonen",
      owner: "Arnoud",
      phaseId: "acceptatieconv",
      isGroupRow: false,
      status: "not_started",
      barType: "task",
      startWeek: 23,
      startYear: 2026,
      endWeek: 26,
      endYear: 2026,
      isMilestone: false,
      sortOrder: 80,
    },
    {
      id: "task-2-17",
      projectNumber: "2.17",
      description: "Totaalcontroles Hof Wonen",
      owner: "Faridda",
      phaseId: "testen_acc_h",
      isGroupRow: false,
      status: "not_started",
      barType: "task",
      startWeek: 27,
      startYear: 2026,
      endWeek: 30,
      endYear: 2026,
      isMilestone: false,
      sortOrder: 90,
    },
    {
      id: "task-2-18",
      projectNumber: "2.18",
      description: "Detailcontroles Hof Wonen",
      owner: "Faridda",
      phaseId: "testen_acc_h",
      isGroupRow: false,
      status: "not_started",
      barType: "task",
      startWeek: 28,
      startYear: 2026,
      endWeek: 32,
      endYear: 2026,
      isMilestone: false,
      sortOrder: 100,
    },
    {
      id: "task-2-19",
      projectNumber: "2.19",
      description: "Proefprolongatie Hof Wonen",
      owner: "Faridda",
      phaseId: "testen_acc_h",
      isGroupRow: false,
      status: "not_started",
      barType: "task",
      startWeek: 30,
      startYear: 2026,
      endWeek: 34,
      endYear: 2026,
      isMilestone: false,
      sortOrder: 110,
    },
    {
      id: "task-2-20",
      projectNumber: "2.20",
      description: "Aanlevering GRIP en CRM Stedelink en Hof Wonen",
      owner: "Faridda",
      phaseId: "testen_acc_h",
      isGroupRow: false,
      status: "not_started",
      barType: "task",
      startWeek: 29,
      startYear: 2026,
      endWeek: 33,
      endYear: 2026,
      isMilestone: false,
      sortOrder: 120,
    },
    {
      id: "task-2-22",
      projectNumber: "2.22",
      description: "Migratie Stedelink en Hof Wonen",
      owner: "Arnoud",
      phaseId: "testen_acc_h",
      isGroupRow: false,
      status: "not_started",
      barType: "task",
      startWeek: 31,
      startYear: 2026,
      endWeek: 35,
      endYear: 2026,
      isMilestone: false,
      sortOrder: 130,
    },
    {
      id: "task-2-23",
      projectNumber: "2.23",
      description: "Totaalcontroles Stedelink Wonen",
      owner: "Faridda",
      phaseId: "trainen_hof",
      isGroupRow: false,
      status: "not_started",
      barType: "task",
      startWeek: 36,
      startYear: 2026,
      endWeek: 38,
      endYear: 2026,
      isMilestone: false,
      sortOrder: 140,
    },
    {
      id: "task-2-24",
      projectNumber: "2.24",
      description: "Detailcontroles Stedelink en Hof Wonen",
      owner: "Faridda",
      phaseId: "trainen_hof",
      isGroupRow: false,
      status: "not_started",
      barType: "task",
      startWeek: 36,
      startYear: 2026,
      endWeek: 39,
      endYear: 2026,
      isMilestone: false,
      sortOrder: 150,
    },
    {
      id: "task-2-25",
      projectNumber: "2.25",
      description: "Proefprolongatie Stedelink Wonen",
      owner: "Faridda",
      phaseId: "trainen_hof",
      isGroupRow: false,
      status: "not_started",
      barType: "task",
      startWeek: 37,
      startYear: 2026,
      endWeek: 39,
      endYear: 2026,
      isMilestone: false,
      sortOrder: 160,
    },
    {
      id: "task-vrijgave",
      projectNumber: "2.26",
      description:
        "Vrijgave testomgevingen en naar volgende fase: onboarding",
      owner: "Faridda",
      phaseId: "trainen_hof",
      isGroupRow: false,
      status: "not_started",
      barType: "task",
      startWeek: 38,
      startYear: 2026,
      endWeek: 39,
      endYear: 2026,
      isMilestone: false,
      sortOrder: 170,
    },
    {
      id: "milestone-livegang-hof",
      projectNumber: "M.1",
      description: "Go/No-Go Livegang Hof Wonen",
      owner: "Faridda",
      phaseId: "livegang_hof",
      isGroupRow: false,
      status: "not_started",
      barType: "critical_milestone",
      startWeek: 42,
      startYear: 2026,
      endWeek: 42,
      endYear: 2026,
      isMilestone: true,
      sortOrder: 180,
    },
    {
      id: "milestone-livegang-stedelink",
      projectNumber: "M.2",
      description: "Go/No-Go Livegang Stedelink",
      owner: "Arnoud",
      phaseId: "livegang_stedelink",
      isGroupRow: false,
      status: "not_started",
      barType: "critical_milestone",
      startWeek: 49,
      startYear: 2026,
      endWeek: 49,
      endYear: 2026,
      isMilestone: true,
      sortOrder: 190,
    },
    {
      id: "holiday-summer",
      projectNumber: "",
      description: "Vakantieperiode zomer",
      owner: "",
      phaseId: "testen_acc_h",
      isGroupRow: false,
      status: "not_started",
      barType: "holiday",
      startWeek: 28,
      startYear: 2026,
      endWeek: 32,
      endYear: 2026,
      isMilestone: false,
      sortOrder: 5,
    },
    {
      id: "decision-1",
      projectNumber: "D.1",
      description: "Inhoudelijke besluitvorming acceptatiefase",
      owner: "Arnoud",
      phaseId: "acceptatieconv",
      isGroupRow: false,
      status: "not_started",
      barType: "decision",
      startWeek: 23,
      startYear: 2026,
      endWeek: 24,
      endYear: 2026,
      isMilestone: false,
      sortOrder: 85,
    },
  ];

  for (const t of taskDefs) {
    await prisma.task.create({ data: t });
  }

  console.log(`Created ${taskDefs.length} tasks`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
